# Generated by Django 2.0 on 2020-01-14 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
