# Generated by Django 2.0 on 2020-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autotest', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True, verbose_name='project_code')),
                ('project_name', models.CharField(max_length=255, verbose_name='project_name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('effective_flag', models.CharField(choices=[('1', '有效'), ('0', '无效')], max_length=255, verbose_name='effective_flag')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='time_updated')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'project',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
