# Generated by Django 2.0 on 2020-01-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0005_auto_20200114_0958'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job_result',
            table='Job_result',
        ),
    ]
