# Generated by Django 2.0 on 2020-01-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0006_auto_20200114_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_excepte_excuted', models.DateTimeField(auto_now_add=True, verbose_name='期望执行时间')),
                ('last_status', models.CharField(choices=[('1', '未执行'), ('2', '执行中'), ('3', '执行异常'), ('4', '执行完成')], max_length=255, verbose_name='执行结果')),
                ('description', models.CharField(max_length=255, verbose_name='描述/备注')),
                ('effective_flag', models.CharField(choices=[('1', '有效'), ('0', '无效')], max_length=255, verbose_name='是否有效')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cronjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotest.CronJob', verbose_name='所属定时任务')),
            ],
            options={
                'db_table': 'Subtask',
                'verbose_name': '定时任务的子任务',
                'verbose_name_plural': '定时任务的子任务',
            },
        ),
    ]
