# Generated by Django 2.0 on 2020-01-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0007_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjob',
            old_name='last_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='last_status',
            new_name='status',
        ),
    ]
